name: selenium

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'
  # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checking out repo
        uses: actions/checkout@v4
      - name: setting up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: 'Install requirements'
        run: |
          pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: Running the Python script
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python main.py
      - name: Commit and Push The Results From Action
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "154030812+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "GitHub Actions Results added"
          git push
